### ISSUE TITLE
ImportError: No module named rospkg

### ISSUE THREAD

**Issue by kochigami** [kochigami/my_tutorial#25]
```
roslaunch naoqi_pose pose_manager.launch
Traceback (most recent call last):
  File "/opt/ros/indigo/lib/naoqi_pose/pose_controller.py", line 37, in <module>
    import rospy
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/__init__.py", line 49, in <module>
    from .client import spin, myargv, init_node, \
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/client.py", line 52, in <module>
    import roslib
  File "/opt/ros/indigo/lib/python2.7/dist-packages/roslib/__init__.py", line 50, in <module>
    from roslib.launcher import load_manifest
  File "/opt/ros/indigo/lib/python2.7/dist-packages/roslib/launcher.py", line 42, in <module>
    import rospkg
ImportError: No module named rospkg
Traceback (most recent call last):
  File "/opt/ros/indigo/lib/naoqi_pose/pose_manager.py", line 33, in <module>
    import rospy
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/__init__.py", line 49, in <module>
    from .client import spin, myargv, init_node, \
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/client.py", line 52, in <module>
    import roslib
  File "/opt/ros/indigo/lib/python2.7/dist-packages/roslib/__init__.py", line 50, in <module>
    from roslib.launcher import load_manifest
  File "/opt/ros/indigo/lib/python2.7/dist-packages/roslib/launcher.py", line 42, in <module>
    import rospkg
ImportError: No module named rospkg
```
http://stackoverflow.com/questions/22585235/python-anaconda-how-to-safely-uninstall/40159908#40159908
原因はanacondaのパス（.bashrc）

http://answers.ros.org/question/39657/importerror-no-module-named-rospkg/
の下の方でも困っている人がいる。pip install するといいらしい

**Comment by Miha22** [comment]
This is an issue because Ubuntu 20.04 has dropped python and python2, and now using python 3. Install the following lib to run ROS on Ubuntu 20.04: `sudo apt install python-is-python3`
