### ISSUE TITLE
[tf transformation]

### ISSUE THREAD

**Issue by kochigami** [kochigami/my_tutorial#31]
認識した物（bounding box）にboxという新しいframeを作って、
カメラフレームとの間でtfを出していて、

    tf_monitorで出てくる
    rvizのtf表示でも見える
    のに、

プログラム実行すると、waitForTransform でエラーが出てしまいます。（10秒間tfが検出されない、と言っています。）

tf_monitor
```
 rosrun tf tf_monitor CameraTop_optical_frame box

RESULTS: for CameraTop_optical_frame to box
Chain is: CameraTop_optical_frame -> box
Net delay     avg = 161.71: max = 162.709

Frames:
Frame: CameraTop_optical_frame published by unknown_publisher Average Delay: 0.00372446 Max Delay: 0.0586254
Frame: box published by unknown_publisher Average Delay: 0.000725357 Max Delay: 0.00119423

All Broadcasters:
Node: unknown_publisher 15.6659 Hz, Average Delay: 0.00366741 Max Delay: 0.0579001
```
rviz
![screenshot from 2017-04-14 20 39 27](https://cloud.githubusercontent.com/assets/7259671/25042484/60bc4996-2153-11e7-883c-adcd1f06a345.png)

error
```
python learn_tf.py

[ERROR] [WallTime: 1492170045.063782] bad callback: <function detected_person_position_callback at 0x7f512c1eb668>
Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/topics.py", line 720, in _invoke_callback
    cb(msg)
  File "learn_tf.py", line 60, in detected_person_position_callback
    listener.waitForTransform("CameraTop_optical_frame", "box", now, rospy.Duration(10.0)) # from to
Exception: Lookup would require extrapolation into the past.  Requested time 1492170035.061646938 but the earliest data is at time 1492170035.085304499, when looking up transform from frame [box] to frame [CameraTop_optical_frame]. canTransform returned after 10.0019 timeout was 10.

[ERROR] [WallTime: 1492170049.260884] bad callback: <function detected_person_position_callback at 0x7f512c1eb668>
Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/topics.py", line 720, in _invoke_callback
    cb(msg)
  File "learn_tf.py", line 27, in detected_person_position_callback
    listener.waitForTransform("CameraTop_optical_frame", "box", rospy.Time(), rospy.Duration(4.0))
Exception: . canTransform returned after 4.00346 timeout was 4.
```

**Comment by kochigami** [comment]
認識した物（bounding box）にboxという新しいframeを作って、
カメラフレームとの間でtfを出していて、

- tf_monitorで出てくる
- rvizのtf表示でも見える
のに、

プログラム実行すると、``` waitForTransform``` でエラーが出てしまいます。（10秒間tfが検出されない、と言っています。）


tf_monitor
```
 rosrun tf tf_monitor CameraTop_optical_frame box

RESULTS: for CameraTop_optical_frame to box
Chain is: CameraTop_optical_frame -> box
Net delay     avg = 161.71: max = 162.709

Frames:
Frame: CameraTop_optical_frame published by unknown_publisher Average Delay: 0.00372446 Max Delay: 0.0586254
Frame: box published by unknown_publisher Average Delay: 0.000725357 Max Delay: 0.00119423

All Broadcasters:
Node: unknown_publisher 15.6659 Hz, Average Delay: 0.00366741 Max Delay: 0.0579001
```
rviz
![screenshot from 2017-04-14 20 39 27](https://cloud.githubusercontent.com/assets/7259671/25042484/60bc4996-2153-11e7-883c-adcd1f06a345.png)

error
```
python learn_tf.py

[ERROR] [WallTime: 1492170045.063782] bad callback: <function detected_person_position_callback at 0x7f512c1eb668>
Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/topics.py", line 720, in _invoke_callback
    cb(msg)
  File "learn_tf.py", line 60, in detected_person_position_callback
    listener.waitForTransform("CameraTop_optical_frame", "box", now, rospy.Duration(10.0)) # from to
Exception: Lookup would require extrapolation into the past.  Requested time 1492170035.061646938 but the earliest data is at time 1492170035.085304499, when looking up transform from frame [box] to frame [CameraTop_optical_frame]. canTransform returned after 10.0019 timeout was 10.

[ERROR] [WallTime: 1492170049.260884] bad callback: <function detected_person_position_callback at 0x7f512c1eb668>
Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/topics.py", line 720, in _invoke_callback
    cb(msg)
  File "learn_tf.py", line 27, in detected_person_position_callback
    listener.waitForTransform("CameraTop_optical_frame", "box", rospy.Time(), rospy.Duration(4.0))
Exception: . canTransform returned after 4.00346 timeout was 4.
```

プログラムの抜粋（コールバック関数の中で書いています）
```
       listener = tf.TransformListener()
       br = tf.TransformBroadcaster()
       br.sendTransform((box.pose.position.x, box.pose.position.y, box.pose.position.z),
                                     (box.pose.orientation.x, box.pose.orientation.y, box.pose.orientation.z, box.pose.orientation.w),                                   
                                     rospy.Time.now(),
                                     "box", # to                                                                                                 
                                     "CameraTop_optical_frame") # from
       listener.waitForTransform("box", "CameraTop_optical_frame", rospy.Time(), rospy.Duration(4.0))
       try:
            now = rospy.Time.now()
            listener.waitForTransform("box", "CameraTop_optical_frame", now, rospy.Duration(10.0)) # to from                         
            (box_trans, box_rot) = listener.lookupTransform("box", "CameraTop_optical_frame", now) # from to 
       except (tf.LookupException,
                   tf.ConnectivityException,
		   tf.ExtrapolationException) as e:
               print(e)
               pass
```

**Comment by kochigami** [comment]
broadcasterとlistenerを同じプログラムに書かず、分けて書くことで解決した。
